config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

 # devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :categories
  resources :classifieds
  resources :movies
  resources :directors

  get :search, controller: :classifieds
  get :contact, controller: :classifieds
  get 'welcome/index'
  root 'welcome#index'
  get 'auth/:provider/callback', to: 'sessions#create'
 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callback" }
 
  
end

app/models/classified.rb
class Classified < ApplicationRecord
validates_presence_of :title 
    validates_presence_of :price 
    validates_presence_of :location 
    validates_presence_of :description 
    validates_presence_of :email 
    validates_numericality_of :price 
    validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
    
    belongs_to :category 
    
  protected 
    def validate 
      errors.add(:price, "should be a positive value") if price.nil? || price < 0.01 
    end 
  end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  before_action :set_classified, only: [:show, :edit, :update, :destroy]

  # GET /classifieds
  # GET /classifieds.json
  def index
    @classifieds = Classified.all
    @categories = Category.all

  end

  # GET /classifieds/1
  # GET /classifieds/1.json
  def show
      
   @classified = Classified.find(params[:id]) 
   rescue ActiveRecord::RecordNotFound => e

  end

  # GET /classifieds/new
  def new
    @classified = Classified.new
  end

  # GET /classifieds/1/edit
  def edit
  end


  def search
  #  if params[:keywords].present?
    #@keywords = params[:keywords]
    @classifieds = Classified.ransack(title_cont: params[:q]).result(distinct: true).limit(5)
    @categories = Category.ransack(name_cont: params[:q]).result(distinct: true).limit(5)
   
    respond_to do |format|
      format.html {}
      format.json {
        @classifieds = @classifieds.limit(5)
        @categories = @categories.limit(5)
      }
    end
   
end

private 
def force_json
  request.format = :json
end
  # POST /classifieds
  # POST /classifieds.json
  def create
    @classified = Classified.new(classified_params)
    respond_to do |format|
      if @classified.save
        format.html { redirect_to @classified, notice: 'Classified was successfully created.' }
        format.json { render :show, status: :created, location: @classified }
      else
        format.html { render :new }
        format.json { render json: @classified.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classifieds/1
  # PATCH/PUT /classifieds/1.json
  def update
    respond_to do |format|
      if @classified.update(classified_params)
        format.html { redirect_to @classified, notice: 'Classified was successfully updated.' }
        format.json { render :show, status: :ok, location: @classified }
      else
        format.html { render :edit }
        format.json { render json: @classified.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classifieds/1
  # DELETE /classifieds/1.json
  def destroy
    @classified.destroy
    respond_to do |format|
      format.html { redirect_to classifieds_url, notice: 'Classified was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classified
      @classified = Classified.find(params[:id])
    end


    def show_category 
      @category = Category.find(params.fetch[:id]) 
      logger.debug "New post: #{  @category.attributes.inspect}"
      logger.debug "Post should be valid: #{@category.valid?}"
    end


    def contact
      @classified = Classified.find(params[:id])
      ClassifiedMailer.deliver_contact(@classified,params[:contact])
      return if request.xhr?
      render :nothing => true
      end
      
    # Never trust parameters from the scary internet, only allow the white list through.
    def classified_params
    params.require(:classified).permit(:title, :price, :location, :description, :email, :category_id)
    end
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/views/classifieds/_classified.html.erb
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
    <% if @classifieds.blank? %> 
	<p>There are not any ads currently in the system.</p> 
<% else %> 
	<p>These are the current classified ads in our system</p> 

		<% @classifieds.each do |c| %> 
    <tr>
			<td><%= link_to c.title, classified_url(:id => c.id) -%></td>
			<td>	<small> <%= link_to 'Edit', {:action => "edit", :id => c.id} %></small></td>
			<td>	<small><%= link_to 'delete', c, method: :delete, data: { confirm: 'Are you sure?' } %></small> </td>
		<% end %> 
	</tr> 
<% end %> 
  </tbody>
</table>

app/views/classifieds/_form.html.erb
<%= form_with(model: classified, local: true) do |form| %>
  <% if classified.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classified.errors.count, "error") %> prohibited this classified from being saved:</h2>

      <ul>
      <% classified.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :classified_title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :classified_price %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :classified_location %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :classified_description %>
  </div>

<p><label for="classified_category">Category</label><br/> 
<%=collection_select(:classified, :category_id, Category.all.collect,:id, :name) %></p>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :classified_email %>
  </div>

  <div class="actions">
    <%= form.submit "Create" %>
  </div>
<% end %>

app/views/classifieds/edit.html.erb
<h1>Editing Classified</h1>

<%= render 'form', classified: @classified %>

<%= link_to 'Show', @classified %> |
<%= link_to 'Back', classifieds_path %>

app/views/classifieds/index.html.erb
<p id="notice"><%= notice %></p>

<ul class="list-group" id="categories"> 
<%  @categories.each do |c| %> 

<li class="list-group-item d-flex justify-content-between align-items-center">  <%= link_to c.name , :controller=>'categories',:action =>  'show', :id => c.id %></li> <br/> 

  <% end %> 
</ul> 

    <%= form_with url: search_path, local: true, method: :get, html: { class: "form-inline my-2 my-lg-0" } do |form| %>
      <%= form.text_field :q, placeholder: "Search", data: { behavior: "autocomplete" }, class: "form-control mr-sm-2" %>
      <%= form.button "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>


<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @classifieds.blank? %> 
  <p>There are not any ads currently in the system.</p> 
<% else %> 
  <p>These are the current classified ads in our system</p> 

    <% @classifieds.each do |c| %> 
    <tr>
      <td><%= link_to c.title, classified_url(:id => c.id) -%></td>
      <td>  <small> <%= link_to 'Edit', {:action => "edit", :id => c.id} %></small></td>
      <td>  <small><%= link_to 'delete', c, method: :delete, data: { confirm: 'Are you sure?' } %></small> </td>
    <% end %> 
  </tr> 
<% end %> 
  </tbody>
</table>

<br>

<%= link_to 'New Classified', new_classified_path %>

app/views/classifieds/new.html.erb
<h1>New Classified</h1>

<%= render 'form', classified: @classified %>

<%= link_to 'Back', classifieds_path %>

app/views/classifieds/search.html.erb
<div class="row">
  <div class="col">
    <h1>Classifieds</h1>
    <% @classifieds.each do |classified| %>
      <p><%= link_to classified.title, classified %></p>
    <% end %>
  </div>

  <div class="col">
    <h1>Categories</h1>
    <% @categories.each do |category| %>
      <p><%= link_to category.name, category %></p>
    <% end %>
  </div>
</div>

app/views/classifieds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @classified.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@classified.price,{:unit => "$", :separator => ".", :delimiter => ","}) %>
</p>

<p>
  <strong>Location:</strong>
  <%= @classified.location %>
</p>
<%= debug @classified %>

<strong>Category: </strong> <%= link_to @classified.category.name,:controller =>'categories', :action => 'show', :id=>@classified.category.id%><br/> 

<p>
  <strong>Description:</strong>
  <%= @classified.description %>
</p>

<p>
  <strong>Email:</strong>
  <%= @classified.email %>
</p>
<p>
<strong>Date Posted:</strong>
<%= distance_of_time_in_words_to_now(@classified.created_at) %><br />
<strong>Last updated:</strong>
<%= distance_of_time_in_words(@classified.updated_at, Time.now) %></p>
</p>

<p>Interested?
Contact <%= mail_to @classified.email %></p>







<%= link_to 'Edit', edit_classified_url(@classified) %> |
<%= link_to 'Back', :controller=>'classifieds',:action=>'index' %>


<!--
# Submits title=X&description=Y
form_with(url: different_path, class: 'something', id: 'specific') do |form|
  form.text_field :title, 'This has is the value of the title'

  form.text_area :description, class: 'No value has been supplied here'

  form.fields(:permission) do |fields|
    # on/off instead of positional parameters for setting values
    fields.check_box :admin, on: 'yes', off: 'no'
  end

-->